#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: "true"
#    properties:
#      hibernate:
#        dialect: "org.hibernate.dialect.MySQL5Dialect"
#  database:
#    driverClassName: "com.mysql.jdbc.Driver"
#  datasource:
#    url: "jdbc:mysql://localhost:3306/itemsharingdatabase"
#    username: "root"
#    password: "root"
#    testWhileIdle: "true"
#    validationQuery: "SELECT 1"
#    
#security:
#  basic:
#    enabled: false
#
#server:
#  port: 8082
# 

#Setting the logging levels for the service
#logging:
#  level:
#    com.netflix: WARN
#    org.springframework.web: WARN
#    com.itemsharing: DEBUG
#
#security:
#  oauth2:
#    resource:
#      userInfoUri: http://localhost:8901/user