server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/springmicro/config-repo
          username: springmicro
          password: password123
          search-paths: userservice, itemservice
        encrypt:
          enabled: false